- package-lock.json
- package.json
- seeders/20210301053626-users-seed-file.js
- seeders/20210301053656-tweets-seed-file.js
- seeders/20210301053707-replies-seed-file.js
setting up for seed files, please check it, thanks
> install faker, bcryptjs & setup seed files

- app.js
- controllers/api/adminController.js
- controllers/api/followController.js
- controllers/api/likeController.js
- controllers/api/replyController.js
- controllers/api/tweetController.js
- controllers/api/userController.js
- routes/apis.js
- routes/index.js
創建routes/apis.js 以及 index.js
按照路由規劃創建每一個Controller
> Create controllers and routes

- models/like.js
> hotfix for Like model issue

- migrations/20190115071421-create-user.js
修正 user model 屬性 role 的 default value
> hotfix for User model role default value

- Procfile
- app.js
- config/config.json
- package-lock.json
- package.json
setup for heroku & ClearDB
https://twitterkiller-backend.herokuapp.com/
> Setup heroku clear db

- controllers/api/adminController.js
- routes/apis.js
- services/adminService.js
- test/requests/admin.sepc.js
adminService feature finish, please check, thanks!
> Setup admin controller

- config/passport.js
- controllers/api/userController.js
- routes/apis.js
- services/userService.js
新增passport認證
完成getTopUser
手動新增資料測試通過
> set passport & userService.getTopUser

- routes/apis.js
- services/userService.js
> Hotfix user controller

- controllers/api/tweetController.js
- routes/apis.js
- services/tweetService.js
tweetService 已完成，並改寫 async / await，請查收
> Setup tweet controller

- controllers/api/followController.js
- models/followship.js
- routes/apis.js
- services/followService.js
- test/requests/followship.spec.js
> Setup follow controller

- controllers/api/likeController.js
- routes/apis.js
- services/likeService.js
> Setup like controller

- controllers/api/replyController.js
- routes/apis.js
- services/replyService.js
> Setup reply controller

- app.js
- config/passport.js
- controllers/api/userController.js
- routes/apis.js
針對 passport, token 認證的一些測試，沒什麼大變動
postman 測試過可以運行，但還需要跟前端串接看看
> hotfix for autheticated setting

- app.js
- package-lock.json
- package.json
- routes/apis.js
- services/tweetService.js
CORS setup & some feature adjustment
> Setup cors

- seeders/20210301053626-users-seed-file.js
- seeders/20210305143630-followships-seed-file.js
- seeders/20210305143636-Likes-seed-file.js
> add like & followship seed files

- services/tweetService.js
> modify getTweet feature

- routes/apis.js
補上replies的認證
配合test調整authenticatedAdmin 以及 authenticate
> modify AuthenticatedAdmin for test

- app.js
- config/swagger.json
- package-lock.json
- package.json
> add swagger-UI for API doc

- services/followService.js
- services/userService.js
> fix putUser algorithm

- config/swagger.json
- services/userService.js
- 修正 API 文件內容
- 修正了 putUser 內的一個語法
> Swagger UI refactor

- services/adminService.js
- services/followService.js
- services/likeService.js
- services/replyService.js
- services/tweetService.js
- services/userService.js
1. 將userService統一為 async / await
2. 統一status code 500 的error回傳內容
3. 新增isFollowed 到 getFollowers & getFollowings
> userService to async await

- app.js
- config/passport.js
- services/adminService.js
- services/userService.js
> modify unusefull code

- seeders/20210301053656-tweets-seed-file.js
- services/userService.js
> modify tweet seed files and userService

- services/userService.js
> modify callback data of userService.getfollowers & getfollowings  

- services/adminService.js
新增了刪除tweets之後，連動刪除reply, like 功能
> modify deleteTweets for adminService

- services/adminService.js
> modify adminService.deleteTweets

- services/adminService.js
修改了 adminService 的 getUsers 撈資料邏輯
> modify getUsers for adminService

- services/userService.js
修正getTopUser
簡化getFollowers/getFollowings
> modify userService.getTopUser
